apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: vault-secrets-operator
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.7.1
  values:
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"