apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: jellyfin
  helmVersion: v3
  chart:
    repository: https://billimek.com/billimek-charts/
    name: jellyfin
    version: 1.0.3
  values:
    image:
      tag: latest
    timezone: America/New_York
    service:
      type: LoadBalancer
      loadBalancerIP: 10.100.10.220
      port: 80
      annotations:
        metallb.universe.tf/address-pool: public
    persistence:
      movies:
        size: 2000Gi
      tvshows:
        size: 100Gi