apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: jellyfin
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jellyfin
    version: 2.0.1
  values:
    image:
      tag: latest
    timezone: America/New_York
    service:
      type: LoadBalancer
      loadBalancerIP: 10.100.10.220
      port: 80
      annotations:
        metallb.universe.tf/address-pool: public
    persistence:
      config:
        size: 1Gi
        storageClass: rook-ceph-block
        skipuninstall: true
      movies:
        enabled: false
        #existingClaim: media-data
        #size: 2000Gi
      tvshows:
        enabled: false
        #existingClaim: media-data
        #size: 100Gi
      extraExistingClaimMounts:
        - name: data
          mountPath: /data-local
          existingClaim: media-data
    nodeSelector:
      storage: ceph #Makes sure to choose the separate server, change this on server upgrade