---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    #image: ceph/ceph:v16.2
    image: ceph/ceph:v15.2.11
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: true
  mon:
    count: 3
    allowMultiplePerNode: true
  monitoring:
    enabled: true
  crashCollector:
    disable: true
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
  resources:
    api:
      requests:
          cpu: 50m
          memory: 250Mi
      limits:
        memory: 2048Mi
    mgr:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 4096Mi
    mon:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        memory: 4096Mi
    osd:
      requests:
        cpu: 200m
        memory: 4096Mi
      limits:
        cpu: 1500m
        memory: 8192Mi
    rbdmirror:
      requests:
          cpu: 25m
          memory: 250Mi
      limits:
        memory: 1024Mi
  storage:
    nodes:
      - name: "10.100.10.11"
        devices:
          - name: "/dev/hdd-12tb-1"
          #- name: "/dev/hdd-12tb-2"
          #  config:
          #    metadataDevice: ""
          #    databaseSizeMB: "0"
          #- name: "/dev/hdd-12tb-3"
          - name: "/dev/hdd-14tb-1"
          - name: "/dev/hdd-14tb-2"
          - name: "/dev/ssd-1tb-1"
          - name: "/dev/ssd-1tb-2"
         # - name: "/dev/nvme2n1"
        #  - name: "/dev/nvme2n1" #TODO: Change this to symlink when it's working
    useAllNodes: false
    useAllDevices: false
    config:
      #metadataDevice: "nvme2n1"
      metadataDevice: "nvme-1tb-1"
      osdsPerDevice: "1"
      #walSizeMB: "20000" #I read that WAL is stored with DB if not specified
      databaseSizeMB: "80000" 