---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      #repository: ghcr.io/k8s-at-home/lidarr
      repository: linuxserver/lidarr
      #tag: v0.8.0.2074
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block-retain"
        accessMode: ReadWriteOnce
        size: "15Gi"
    additionalVolumeMounts:
    - name: media-data
      mountPath: "/media"
    additionalVolumes:
    - name: media-data
      persistentVolumeClaim:
        claimName: media-nfs-write
    resources:
      requests:
        memory: 100Mi
        cpu: 200m
      limits:
        memory: 1000Mi
  valuesFrom:
    - kind: Secret
      name: lidarr-helm-values