apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sia-data
  namespace: blockchain
spec:
  resources:
    requests:
      storage: 60Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-ssd
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sia-hosted
  namespace: blockchain
spec:
  resources:
    requests:
      storage: 4Ti
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce