apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
      interval: 5m
  values:
    csi:
      rbdGrpcMetricsPort: 9093
      cephfsGrpcMetricsPort: 9092 #9091 is already used by Cilium/Hubble