apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi-poller
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.0.1
    prometheus:
      serviceMonitor:
        enabled: true
        interval: 2m
  valuesFrom:
    - kind: Secret
      name: unifi-poller-helm-values