apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-retain
  resources:
    requests:
      storage: 1000Gi