apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 2.5.12
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    metrics:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    resources:
      requests:
        memory: 4Gi
        cpu: "600m"
      limits:
        memory: 8Gi
        cpu: "1500m"
    #nextcloud:
    #  extraEnv:
    #  - name: OVERWRITEPROTOCOL
    #    value: https
  valuesFrom:
    - kind: Secret
      name: nextcloud-helm-values