apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-nextcloud
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 10.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    postgresqlDatabase: nextcloud
    persistence:
      storageClass: rook-ceph-ssd
      size: 20G
  valuesFrom:
    - kind: Secret
      name: postgresql-helm-values


# Converting from sqlite to postgresql:
# on node pod is running 
# docker exec -it --user www-data <CONTAINER ID> bash
# php occ db:convert-type --port 5432 pgsql nextcloud postgresql-nextcloud nextcloud