---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-blockchain
  namespace: blockchain
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce