---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: navidrome
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      config:
        enabled: true
        existingClaim: navidrome-config
      music:
        enabled: true
        existingClaim: media-nfs-readonly
        #mountPath: /music
    env:
      ND_MUSICFOLDER: /music/music
  valuesFrom:
    - kind: Secret
      name: navidrome-helm-values