apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
