apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: lan-only
  namespace: networking
spec:
  chain:
    middlewares:
    - name: any-lan
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: any-lan
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
    - 10.100.0.0/16
    - 10.43.0.0/16
    - 10.0.0.0/16