apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-only
  namespace: networking
spec:
  chain:
    middlewares:
    - name: internal-ips
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
    - 10.100.10.0/24
    - 10.43.0.0/16
    - 10.0.0.0/16