apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: media
spec:
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-ssd-no-replica
  accessModes:
    - ReadWriteOnce