apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs-mount
  namespace: media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.100.10.17
    path: "/media-data"
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-nfs-mount
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi