---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 9.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      # Keep for VPN
      repository: k8sathome/qbittorrent
      tag: v4.3.3
      pullPolicy: Always
    env:
      TZ: "America/New_York"
      WAIT_FOR_VPN: "true"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "5Gi"
      shared:
        enabled: true
        emptyDir: true  
        mountPath: /shared
    #podAnnotations:
    #  backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: media-data
      mountPath: "/media"
    additionalVolumes:
    - name: media-data
      persistentVolumeClaim:
        claimName: media-nfs-write
    resources:
      requests:
        memory: 3000Mi
        cpu: 500m
      limits:
        memory: 8000Mi
  valuesFrom:
    - kind: Secret
      name: qbittorrent-helm-values