apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
  namespace: blockchain
spec:
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - name: bitcoin
        image: jamesob/bitcoind
        resources:
          requests:
              memory: "2048Mi"
              cpu: "250m"
          limits:
            memory: "4096Mi"
            cpu: "800m"
        volumeMounts:
        - mountPath: /bitcoin/data
          name: bitcoin-data
        env:
          - name: BITCOIN_RPC_USER
            valueFrom:
              secretKeyRef:
                key: BITCOIN_RPC_USER
                name: BITCOIN_RPC_USER
          - name: BITCOIN_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                key: BITCOIN_RPC_PASSWORD
                name: BITCOIN_RPC_PASSWORD
        ports:
        - containerPort: 8333
      volumes:
      - name: bitcoin-data
        persistentVolumeClaim:
          claimName: btc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-service
  namespace: blockchain
spec:
  selector:
    app: bitcoin
  ports:
  - name: p2p-network
    port: 8333
  type: LoadBalancer
  loadBalancerIP: 10.100.10.223
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btc-pvc
  namespace: blockchain
spec:
  resources:
    requests:
      storage: 420Gi
  accessModes:
    - ReadWriteOnce