apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nextcloud
  helmVersion: v3
  chart:
    repository: https://nextcloud.github.io/helm/
    name: nextcloud
    version: 2.2.1
  values:
    metrics:
      enabled: true
    persistence:
      enabled: true
      size: 1000Gi
      storageClass: rook-ceph-block
    resources:
      requests:
        memory: 4Gi
        cpu: "500m"
      limits:
        memory: 8Gi
        cpu: "1500m"
    nextcloud:
      extraEnv:
      - name: OVERWRITEPROTOCOL
        value: https
  valueFileSecrets:
  - name: "nextcloud-helm-values"