apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: access-mgmt
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-forward-auth
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    replicaCount: 1
    image:
      repository: thomseddon/traefik-forward-auth
      tag: "2.2"
    default:
      provider: "oidc"
    middleware:
      enabled: true
      name: forward-auth
  valuesFrom:
    - kind: Secret
      name: traefik-forward-auth-helm-values