apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice
  namespace: home
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: onlyoffice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: onlyoffice
    spec:
      containers:
        - name: onlyoffice
          image: onlyoffice/documentserver:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1500m"
          ports:
           - containerPort: 80
           - containerPort: 443
          #command: ["/bin/bash", "-c", "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && bash /app/ds/run-document-server.sh"]
          #volumeMounts:
          #  - name: configuration
          #    mountPath: /etc/onlyoffice/documentserver/default.json
          #    readOnly: true
          #    subPath: default.file
      volumes:
        - name: configuration
          configMap:
            defaultMode: 0666
            name: documentserver-license
---
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  namespace: home
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    #- port: 443
    #  targetPort: https
    #  protocol: TCP
    #  name: https
  selector:
    #name: onlyoffice
    app.kubernetes.io/name: onlyoffice