apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: backup
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: v8.0.9
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    mode: standalone
    persistence:
      existingClaim: minio-backup
    DeploymentUpdate:
      type: Recreate
    securityContext:
      enabled: true
    existingSecret: minio-secret
  valuesFrom:
    - kind: Secret
      name: minio-helm-values