apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-backup
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /backup/disk0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: backup-disk
          operator: In
          values: ["yes"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-backup
  namespace: backup
spec:
  resources:
    requests:
      storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage"