---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speedtest-prometheus
  namespace: monitoring
spec:
  releaseName: speedtest-prometheus
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: speedtest-prometheus
    version: 2.0.0
  values:
    serviceMonitor:
      enabled: true
      interval: "60m"