apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: harbor
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: v10.7.11
  values:
    metries:
      enabled: true