---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/sonarr
      #repository: linuxserver/sonarr
      tag: latest
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        #storageClass: "rook-ceph-block-retain"
        #accessMode: ReadWriteOnce
        #size: "25Gi"
        existingClaim: sonarr-config
    additionalVolumeMounts:
    - name: media-data
      mountPath: "/media"
    additionalVolumes:
    - name: media-data
      persistentVolumeClaim:
        claimName: media-nfs-write
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
    - kind: Secret
      name: sonarr-helm-values