apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: monitor.in.sleepingshell.com
    http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 3000
