---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: bazarr
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "5Gi"
    #podAnnotations:
    #  backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: media-data
      mountPath: "/media"
    additionalVolumes:
    - name: media-data
      persistentVolumeClaim:
        claimName: media-nfs-write
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
    - kind: Secret
      name: bazarr-helm-values