---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 8.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/radarr
      tag: v3.0.2.4369
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block-retain"
        accessMode: ReadWriteOnce
        size: "25Gi"
    #podAnnotations:
    #  backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: media-data
      mountPath: "/media"
    additionalVolumes:
    - name: media-data
      persistentVolumeClaim:
        claimName: media-nfs-write
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
    - kind: Secret
      name: radarr-helm-values