---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: backup
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 3.0.8
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    #eula:
    #  accept: true
    global:
      persistence:
        storageClass: rook-ceph-block
    clusterName: k8s
    auth:
      oidcAuth:
        enabled: true
        scopes: "profile email"
        clientID: k10
        usernameClaim: "preferred_username"
    resources:
      requests:
        memory: 250Mi
        cpu: 20m
      limits:
        memory: 2Gi
        cpu: 500m
  valuesFrom: 
    - kind: Secret
      name: "k10-helm-values"

# https://openidconnect.net/
# https://oidcdebugger.com/