---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/jackett
      #tag: v0.17.348
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block-retain"
        accessMode: ReadWriteOnce
        size: "1Gi"
    #podAnnotations:
    #  backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
    - kind: Secret
      name: jackett-helm-values