apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge-data
  namespace: home
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-ssd
  accessModes:
    - ReadWriteOnce
