apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: metallb
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.21
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    configInline:
      address-pools:
      - name: public
        protocol: layer2
        addresses:
        - 10.100.10.220-10.100.10.229