apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      create: true
    replicaCount: 1
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
      - 10.100.10.232
      #loadBalancerIP: "10.100.10.231"
      externalTrafficPolicy: Local
    servers:
    - zones:
      - zone: in.sleepingshell.com.
        scheme: dns://
        # use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: in.sleepingshell.com
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd:2379
    #prometheus:
    #  service:
    #    enabled: true
    #  monitor:
    #    enabled: true
