apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd-dns
  namespace: networking
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 5m
  chart:
    spec:
      chart: etcd
      version: 5.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    statefulset:
      replicaCount: 1
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: false
      # size: 8Gi
    #metrics:
    #  enabled: true
    #  serviceMonitor:
    #    enabled: true