---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speedtest
  namespace: monitoring
spec:
  releaseName: speedtest
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: speedtest
    version: 3.0.0
  values:
    #serviceMonitor:
    #  enabled: true
    #  interval: "60m"
    config:
      influxdb:
        host: influxdb