#helmOperator:
#  create: false
git:
  url: "git@github.com:sleepingshell/kube-gitops"
  pollInterval: "2m"
image:
  repository: docker.io/fluxcd/flux
  tag: 1.19.0
registry:
  rps: 50
  burst: 50
memcached:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux