apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block-retain
  accessModes:
    - ReadWriteOnce