apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: teslamate
  chart:
    repository: https://k8s-at-home.com/charts/
    name: teslamate
    version: 3.0.1
  values:
    timeZone: "America/New_York"
    mqtt:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        #cert-manager.io/cluster-issuer: ca-issuer
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    probes:
      liveness:
        failureThreshold: 15
        periodSeconds: 10
      readiness:
        failureThreshold: 15
        periodSeconds: 10
      startup:
        initialDelaySeconds: 15
        failureThreshold: 30
        periodSeconds: 10
    postgresql:
      image:
        repository: postgres
        tag: 12.1
      persistence:
        enabled: true
        storageClass: rook-ceph-block
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
      #master:
      #  podAnnotations:
      #    backup.velero.io/backup-volumes: data
  valueFileSecrets:
  - name: "teslamate-helm-values"
