apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 25Gi
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
