apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: networking
  annotations:
    fluxcd.io/automated: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    #image:
    #  repository: adguard/adguardhome
    #  tag: edge
    persistence:
      config:
        enabled: false
        size: 10Mi
        storageClass: rook-ceph-block
      work:
        enabled: false
        size: 30Gi
        skipUninstall: true
        storageClass: rook-ceph-block
    timezone: "America/New_York"
    replicas: 1
    ingress:
      enabled: true
      annotations:
        #kubernetes.io/tls-acme: "true"
        #cert-manager.io/cluster-issuer: "letsencrypt-prod"
        external-dns.alpha.kubernetes.io/hostname: "adguard.homielab.me"
      hosts:
      - adguard.homielab.me
      #tls:
      #- hosts:
      #  - adguard.homielab.me
      #  secretName: adguard-cert
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.100.10.235
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceTCP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.100.10.235
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceUDP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.100.10.235
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceDNSOverTLS:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      loadBalancerIP: 10.100.10.235
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
    ################ Adguard Home Config ###########################################
    configAsCode:
      enabled: true
      config:
        bind_host: 0.0.0.0
        bind_port: 3000
        users: []
        http_proxy: ""
        language: ""
        rlimit_nofile: 0
        debug_pprof: false
        web_session_ttl: 720
        dns:
          bind_host: 0.0.0.0
          port: 53
          statistics_interval: 7
          querylog_enabled: true
          querylog_file_enabled: true
          querylog_interval: 7
          querylog_size_memory: 1000
          anonymize_client_ip: false
          protection_enabled: true
          blocking_mode: default
          blocking_ipv4: ""
          blocking_ipv6: ""
          blocked_response_ttl: 10
          parental_block_host: family-block.dns.adguard.com
          safebrowsing_block_host: standard-block.dns.adguard.com
          ratelimit: 0
          ratelimit_whitelist: []
          refuse_any: true
          upstream_dns:
          - '[/homielab.me/]10.100.10.232'
          #- 10.100.10.1
          - 84.200.69.80
          bootstrap_dns:
          #- 1.1.1.1
          all_servers: false
          fastest_addr: true
          allowed_clients: []
          #- 10.100.10.0/24
          #- 10.100.20.0/24
          disallowed_clients: []
          blocked_hosts: []
          cache_size: 4194304
          cache_ttl_min: 0
          cache_ttl_max: 0
          bogus_nxdomain: []
          aaaa_disabled: false
          enable_dnssec: false
          edns_client_subnet: true
          filtering_enabled: true
          filters_update_interval: 1
          parental_enabled: false
          safesearch_enabled: false
          safebrowsing_enabled: true
          safebrowsing_cache_size: 1048576
          safesearch_cache_size: 1048576
          parental_cache_size: 1048576
          cache_time: 30
          rewrites: []
        tls:
          enabled: false
          server_name: ""
          force_https: false
          port_https: 443
          port_dns_over_tls: 853
          allow_unencrypted_doh: false
          strict_sni_check: false
          certificate_chain: ""
          private_key: ""
          certificate_path: ""
          private_key_path: ""
        filters:
        - enabled: true
          url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          name: AdGuard Simplified Domain Names filter
          id: 1
        - enabled: true
          url: https://adaway.org/hosts.txt
          name: AdAway
          id: 2
        - enabled: true
          url: https://hosts-file.net/ad_servers.txt
          name: hpHosts - Ad and Tracking servers only
          id: 3
        - enabled: true
          url: https://www.malwaredomainlist.com/hostslist/hosts.txt
          name: MalwareDomainList.com Hosts List
          id: 4
        - enabled: true
          url: https://dbl.oisd.nl/
          name: Domain Blocklists
          id: 5
        whitelist_filters: []
        user_rules:
        - '@@||md.us^                                # Maryland Schools'
        - '@@||r20.rs6.net^'
        dhcp:
          enabled: false
        log_compress: false
        log_localtime: false
        log_max_backups: 0
        log_max_size: 100
        log_max_age: 3
        log_file: ""
        verbose: false
        schema_version: 6
##################### End Config ###############################################
