apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: networking
  annotations:
    fluxcd.io/automated: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    #image:
    #  repository: adguard/adguardhome
    #  tag: edge
    persistence:
      config:
        enabled: false
        size: 10Mi
        storageClass: rook-ceph-block
      work:
        enabled: false
        size: 30Gi
        skipUninstall: true
        storageClass: rook-ceph-block
    timezone: "America/New_York"
    replicas: 1
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceTCP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceUDP:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    serviceDNSOverTLS:
      enabled: true
      externalTrafficPolicy: Local
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: adguard-home-svc
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valuesFrom:
    - kind: Secret
      name: adguard-helm-values