apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      create: true
    replicaCount: 1
    isClusterService: false
    #prometheus:
    #  service:
    #    enabled: true
    #  monitor:
    #    enabled: true
  valuesFrom:
    - kind: Secret
      name: coredns-helm-values