apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.5.5
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
      interval: 5m
  values:
    csi:
      cephfsGrpcMetricsPort: 9092 #Apparently port 9091 is in use already, but can't find by what