apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: cert-manager
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.14.2
  values:
    installCRDs: true
    webhook:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers=10.100.10.3:53
    - --dns01-recursive-nameservers-only
    cainjector:
      replicaCount: 1
      extraArgs:
        - --leader-elect=false
    #prometheus:
    #  enabled: true
    #  servicemonitor:
    #    enabled: true
    #    namespace: cert-manager