apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
